import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "dist/**",
    // Vendored Monaco build output, generated by scripts/sync-monaco.cjs
    "public/monaco/**",
    "electron/**",
    "next-env.d.ts",
  ]),
  {
    // Build/packaging scripts are plain CommonJS executed by Node, so require() is expected.
    files: ["**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
]);

export default eslintConfig;
